baseURL = 'http://www.amiblocked.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
  homeText = "You just made a Hugo blog from scratch."

[permalinks]
  blog = "/:filename/"

[[deployment.targets]]
URL = "s3://amiblocked.io.website?region=us-east-1"


[deployment]
  [[deployment.targets]]
    name = "aws-s3"
    URL = "s3://amiblocked.io.website?region=us-east-1"
    cloudFrontDistributionID = "E1MBXGD6ZC81E2"

  [[deployment.matchers]]
    pattern = "^sitemap\\.xml$"
    cacheControl = "public, s-maxage=604800, max-age=86400" #7d,1d
    contentType = "application/xml"

  [[deployment.matchers]]
    pattern = "^.+\\.(css|js)$"
    cacheControl = "public, immutable, max-age=31536000" #1y

  [[deployment.matchers]]
    pattern = "(?i)^.+_hu[0-9a-f]{32}_.+\\.(jpg|jpeg|gif|png|webp)$"
    cacheControl = "public, immutable, max-age=31536000" #1y

  [[deployment.matchers]]
    pattern = "(?i)^.+\\.(jpg|jpeg|gif|png|webp|mp4|woff|woff2)$"
    cacheControl = "public, s-maxage=7776000, max-age=604800" #90d,7d

  [[deployment.matchers]]
    pattern = "^.+\\.(html|xml|json|txt)$"
    cacheControl = "public, s-maxage=604800, max-age=3600" #7d,1h
